### PR TITLE
Web Audio wrapper/example

### PR DESCRIPTION
**Pull request by carlosrafaelgn**
Hi everyone!

Just as discussed at #52, I am creating a pull request with the web audio port of libmikmod.

Nothing outside libmikmod/webaudio folder has been changed 😊

### CODE REVIEW

**Comment by sezero** [comment]
Thanks.

Questions:
- libmikmodclib.wasm is the prebuilt binary, yes? Is it wise to include in source tree?
- Is libmikmodclib.wasm the only binary to be built? I mean, if there are changes to
  the source, what (else) should be changed?

**Comment by carlosrafaelgn** [comment]
Hi, @sezero !

Indeed, libmikmodclib.wasm is a prebuilt binary, just as libmikmodprocessor.min.js.

I added these two prebuilt files, along with a third JS file, to the "dist" folder, because that is what most web libraries/frameworks do on GitHub, allowing other developers to quickly download the library to be used in their projects.

But I see your point (future maintenance)... I could just add the "dist" folder to a .gitignore file.

Otherwise, it would be necessary to run these two build scripts (in this order) every time the C files changed:

- libmikmod/webaudio/build/xxx/buildwasm
- libmikmod/webaudio/build/xxx/tscbmin

Should I gitignore the dist folder and push the repo again?

**Comment by sezero** [comment]
Yes please!

**Comment by carlosrafaelgn** [comment]
Done!

**Comment by sezero** [comment]
Thanks, applied.

**Pull request merged**
